# netlify.toml

[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[dev]
  command    = "npm run dev"      # seu comando para iniciar o Vite
  port       = 8888               # porta onde o Netlify UI roda
  targetPort = 8081               # onde o Vite realmente está

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
